services:
  - type: web
    name: lockuapp
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: PYROGRAM_SESSION_STRING
        sync: false
